dist: xenial
os: linux
language: generic
env:
  global:
    - PATH=/opt/rakudo-pkg/bin:/opt/rakudo-pkg/share/perl6/site/bin:$PATH
before_install:
  - wget https://github.com/nxadm/rakudo-pkg/releases/download/v2019.03.1/rakudo-pkg-Ubuntu16.04_2019.03.1-01_amd64.deb
  - sudo dpkg -i rakudo-pkg-Ubuntu16.04_2019.03.1-01_amd64.deb
  - sudo apt-get -qq update
  - sudo apt-get install libarchive13
install:
  - zef install --deps-only --/test .
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/*.t6
